# Generated by Django 4.2.13 on 2026-05-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghg_category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('activity_unit', models.CharField(max_length=50)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ghg_category'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmissionRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_FLIGHT', 'Business Travel — Flight'), ('TRAVEL_HOTEL', 'Business Travel — Hotel'), ('TRAVEL_GROUND', 'Business Travel — Ground')], max_length=30)),
                ('source_ref', models.CharField(blank=True, help_text='Vendor invoice #, PO number, meter ID, or trip ID from source', max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_ingested_at', models.DateTimeField(blank=True, editable=False)),
                ('is_manually_edited', models.BooleanField(default=False, help_text='Set True when an analyst edits normalized values post-ingestion')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Purchased Energy'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('scope3_category', models.IntegerField(blank=True, help_text='GHG Protocol Scope 3 category 1–15; null for Scope 1 & 2', null=True)),
                ('ghg_category', models.CharField(help_text='Fine-grained category matching EmissionFactor.ghg_category', max_length=100)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(help_text='Canonical unit: liters, kWh, km, hotel_night', max_length=50)),
                ('activity_date', models.DateField(help_text='Date the activity occurred (posting date for SAP, transaction date for travel)')),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('location', models.CharField(blank=True, help_text='Plant code, site name, city, or airport pair', max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, help_text='Snapshot of EF at time of calculation (kgCO2e / activity_unit)', max_digits=12)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('total_co2e_kg', models.DecimalField(decimal_places=4, help_text='= activity_quantity × emission_factor_value', max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged — Needs Attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reason', models.CharField(blank=True, choices=[('unit_mismatch', 'Unit mismatch detected'), ('outlier_value', 'Outlier value (> 3σ from batch mean)'), ('missing_ref', 'Missing reference data'), ('duplicate', 'Possible duplicate row'), ('date_gap', 'Gap in reporting period'), ('other', 'Other')], max_length=30)),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.ingestionbatch')),
                ('emission_factor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emissions.emissionfactor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.rawrow')),
            ],
            options={
                'verbose_name': 'historical emission record',
                'verbose_name_plural': 'historical emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_FLIGHT', 'Business Travel — Flight'), ('TRAVEL_HOTEL', 'Business Travel — Hotel'), ('TRAVEL_GROUND', 'Business Travel — Ground')], max_length=30)),
                ('source_ref', models.CharField(blank=True, help_text='Vendor invoice #, PO number, meter ID, or trip ID from source', max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_manually_edited', models.BooleanField(default=False, help_text='Set True when an analyst edits normalized values post-ingestion')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Purchased Energy'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('scope3_category', models.IntegerField(blank=True, help_text='GHG Protocol Scope 3 category 1–15; null for Scope 1 & 2', null=True)),
                ('ghg_category', models.CharField(help_text='Fine-grained category matching EmissionFactor.ghg_category', max_length=100)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(help_text='Canonical unit: liters, kWh, km, hotel_night', max_length=50)),
                ('activity_date', models.DateField(help_text='Date the activity occurred (posting date for SAP, transaction date for travel)')),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('location', models.CharField(blank=True, help_text='Plant code, site name, city, or airport pair', max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, help_text='Snapshot of EF at time of calculation (kgCO2e / activity_unit)', max_digits=12)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('total_co2e_kg', models.DecimalField(decimal_places=4, help_text='= activity_quantity × emission_factor_value', max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged — Needs Attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reason', models.CharField(blank=True, choices=[('unit_mismatch', 'Unit mismatch detected'), ('outlier_value', 'Outlier value (> 3σ from batch mean)'), ('missing_ref', 'Missing reference data'), ('duplicate', 'Possible duplicate row'), ('date_gap', 'Gap in reporting period'), ('other', 'Other')], max_length=30)),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.ingestionbatch')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='ingestion.rawrow')),
            ],
            options={
                'ordering': ['-activity_date', 'source_type'],
                'indexes': [models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'), models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'), models.Index(fields=['organization', 'activity_date'], name='emissions_e_organiz_143c84_idx'), models.Index(fields=['batch'], name='emissions_e_batch_i_f2aa5a_idx')],
            },
        ),
    ]
